### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by balajeerc** [ndepaola/bokeh-candlestick#1]
This is not an issue. I don't know how else to message you to say a HUUGE thanks!

I've been testing out several candlestick plotting solutions from matplotlib, to plotly to the base bokeh chart, and this is the only one that just works.

Delighted. Thanks a ton.

**Comment by ndepaola** [comment]
Hey! Glad to hear this project helped you out. I went through the same cycle of looking at matplotlib / plotly / base bokeh before writing this haha :)
